apiVersion: v1
kind: Service
metadata:
  name: buildkitd
  namespace: buildkit
  labels:
    app.kubernetes.io/name: buildkit
    app.kubernetes.io/component: daemon
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: buildkit
    app.kubernetes.io/component: daemon
  ports:
    - name: grpc
      port: 1234
      targetPort: grpc
      protocol: TCP
